Repository crawl/crawl, pull requests merged in 2018-12, with the labels that each got.

#921 Make giant creatures no longer tear through webs
  crawl-ref/source/traps.cc
Labels: enhancement

#924 Fix display of rotted HP on WebTiles (11759)
  crawl-ref/source/tileweb.cc
Labels: bug

#928 Add three tile colour options to the options guide (11802)
  crawl-ref/docs/options_guide.txt
Labels: bug

#929 Make cloud duration more apparent to console players
  crawl-ref/docs/options_guide.txt
  crawl-ref/source/dungeon-char-type.h
  crawl-ref/source/showsymb.cc
  crawl-ref/source/viewchar.cc
Labels: enhancement, ui
