Repository crawl/crawl, pull requests merged in 2019-04, with the labels that each got.

#1029 Turn off skill targets when aptitudes change from level up (11943)
  crawl-ref/source/player.cc
  crawl-ref/source/skills.cc
Labels: bug

#1027 Warn the player that teleportation doesn't work in gauntlet
  crawl-ref/source/stairs.cc
Labels: vaults

#1042 Fix a couple Engulf-related bugs
  crawl-ref/source/duration-data.h
  crawl-ref/source/duration-type.h
  crawl-ref/source/melee-attack.cc
  crawl-ref/source/mon-death.cc
  crawl-ref/source/movement.cc
  crawl-ref/source/player.cc
Labels: bug

#1036 Add second brand to description for Thermic Engine and Storm Bow
  crawl-ref/source/describe.cc
Labels: bug

#1039 Use high-res app icon on all platforms
  crawl-ref/source/tilesdl.cc
Labels: build, graphics

#1015 Don't assume some identified jewellery is boring
  crawl-ref/source/dat/defaults/autopickup_exceptions.txt
Labels: ui

#1046 Add bolt range behaviour to bolt spell descriptions
  crawl-ref/source/dat/descript/ability.txt
  crawl-ref/source/dat/descript/spells.txt
Labels: ui
