Repository crawl/crawl, pull requests merged in 2019-03, with the labels that each got.

#998 Let barachim use grand finale at range 8 (11917)
  crawl-ref/source/god-abil.cc
Labels: bug

#955 TAG_MAJOR_VERSION improvements
  .gitignore
  crawl-ref/source/ability.cc
  crawl-ref/source/acquire.cc
  crawl-ref/source/art-func.h
  crawl-ref/source/artefact-prop-type.h
  crawl-ref/source/artefact.cc
  crawl-ref/source/daction-type.h
  crawl-ref/source/dactions.cc
  crawl-ref/source/describe-god.cc
  crawl-ref/source/describe-spells.cc
  crawl-ref/source/describe.cc
  crawl-ref/source/dungeon-feature-type.h
  crawl-ref/source/end.cc
  crawl-ref/source/evoke.cc
  crawl-ref/source/feature-data.h
  crawl-ref/source/god-abil.cc
  crawl-ref/source/god-conduct.cc
  crawl-ref/source/god-passive.cc
  crawl-ref/source/god-type.h
  crawl-ref/source/god-wrath.cc
  crawl-ref/source/invent.cc
  crawl-ref/source/item-name.cc
  crawl-ref/source/item-prop-enum.h
  crawl-ref/source/items.cc
  crawl-ref/source/lookup-help.cc
  crawl-ref/source/mapdef.cc
  crawl-ref/source/mon-cast.cc
  crawl-ref/source/mon-death.cc
  crawl-ref/source/mon-ench.cc
  crawl-ref/source/mon-util.cc
  crawl-ref/source/ng-setup.cc
  crawl-ref/source/player-equip.cc
  crawl-ref/source/player.cc
  crawl-ref/source/religion.cc
  crawl-ref/source/rltiles/dc-item.txt
  crawl-ref/source/showsymb.cc
  crawl-ref/source/skills.cc
  crawl-ref/source/spl-cast.cc
  crawl-ref/source/spl-summoning.cc
  crawl-ref/source/tags.cc
  crawl-ref/source/terrain.cc
  crawl-ref/source/transform.cc
  crawl-ref/source/viewchar.cc
  crawl-ref/source/wiz-item.cc
Labels: refactor

#1004 Fix cut-off ability cost description for Sac Purity (11893)
  crawl-ref/source/ability.cc
Labels: bug

#1007 Fix splash noises when dropping item into water
  crawl-ref/source/items.cc
Labels: bug

#994 Prevent allied Shambling Mangroves from constricting themselves (11877)
  crawl-ref/source/mon-cast.cc
Labels: bug

#1017 Let formicids dig statues (Yermak)
  crawl-ref/source/movement.cc
Labels: enhancement

#1016 Fix CMD_MAP_UNFORGET in colemak keybindings
  crawl-ref/settings/colemak_command_keys.txt
Labels: ui

#1019 Don't ignore autopickup settings after autobutcher
  crawl-ref/source/items.cc
Labels: bug

#1020 Add new message for re-corroding a corroded foe
  crawl-ref/source/monster.cc
Labels: ui

#995 Merge Piercer into the storm bow
  crawl-ref/source/art-data.txt
  crawl-ref/source/dat/descript/unrand.txt
  crawl-ref/source/throw.cc
Labels: enhancement
