Repository crawl/crawl, pull requests merged in 2019-11, with the labels that each got.

#1193 Make the game check the floor when emergency eating
  crawl-ref/source/food.cc
Labels: enhancement

#956 Run gdb at lower priority
  crawl-ref/source/crash.cc
Labels: webtiles

#1195 Add some more chaos brand effects
  crawl-ref/source/attack.cc
Labels: enhancement

#1201 Make the Warlock's Mirror's reflection chance scale as intended
  crawl-ref/source/beam.cc
Labels: bug

#1207 Use yaml.safe_load instead of load
  crawl-ref/source/util/species-gen.py
Labels: build
