Repository crawl/crawl, pull requests merged in 2020-04, with the labels that each got.

#1350 Example webtiles systemd unit file
  crawl-ref/source/webserver/contrib/dcss-webtiles.service
Labels: webtiles

#1351 Send DCSS processes SIGABRT rather than SIGTERM
  crawl-ref/source/webserver/process_handler.py
Labels: webtiles

#1340 Adjust Vehumet gift range
  crawl-ref/source/religion.cc
Labels: bug

#1356 Free the crawlies
  crawl-ref/source/dat/des/branches/spider.des
Labels: vaults

#1348 Always save macros
  crawl-ref/source/end.cc
  crawl-ref/source/files.cc
Labels: ui

#1316 A tweak to reactivate layout_cellular_growth
  crawl-ref/source/dat/des/builder/layout_cellular.des
Labels: vaults

#1355 Add the possibility of one more Xom demon
  crawl-ref/source/xom.cc
Labels: enhancement
