Repository crawl/crawl, pull requests merged in 2020-09, with the labels that each got.

#1535 Fix a rampaging bug (12353, Flugkiller)
  crawl-ref/source/movement.cc
Labels: bug

#1560 Fix Hailstorm ally warning prompt (12362)
  crawl-ref/source/spl-damage.cc
Labels: bug

#1547 Give x-v a selection menu when there are many describable things
  crawl-ref/source/directn.cc
  crawl-ref/source/invent.cc
  crawl-ref/source/invent.h
Labels: ui

#1550 Handle dynamic DPI in webtiles glyphs mode
  crawl-ref/source/webserver/game_data/static/cell_renderer.js
  crawl-ref/source/webserver/game_data/static/game.js
Labels: ui, webtiles
