Repository crawl/crawl, pull requests merged in 2020-12, with the labels that each got.

#1624 Fix autofight not prioritizing petrified enemies
  crawl-ref/source/dat/clua/autofight.lua
  crawl-ref/source/l-moninf.cc
Labels: lua, ui

#1620 A small description fix and a story about known shafts
  crawl-ref/source/dat/descript/ability.txt
Labels: text

#1645 Small corrections in the manual
  crawl-ref/docs/crawl_manual.rst
Labels: documentation

#1416 Pass some parameters by reference
  crawl-ref/source/database.cc
  crawl-ref/source/english.cc
  crawl-ref/source/english.h
  crawl-ref/source/game-options.cc
  crawl-ref/source/game-options.h
Labels: refactor
