Repository crawl/crawl, pull requests merged in 2020-07, with the labels that each got.

#1485 Fixes several issues with the xv monster evasion chance calculation.
  crawl-ref/source/attack.cc
  crawl-ref/source/attack.h
  crawl-ref/source/describe.cc
  crawl-ref/source/melee-attack.cc
  crawl-ref/source/melee-attack.h
  crawl-ref/source/ranged-attack.cc
  crawl-ref/source/ranged-attack.h
Labels: ui

#1468 New background: Delver
  crawl-ref/source/dat/descript/backgrounds.txt
  crawl-ref/source/dungeon.cc
  crawl-ref/source/dungeon.h
  crawl-ref/source/job-data.h
  crawl-ref/source/job-type.h
  crawl-ref/source/mgen-enum.h
  crawl-ref/source/mon-place.cc
  crawl-ref/source/newgame.cc
  crawl-ref/source/playable.cc
  crawl-ref/source/rltiles/dc-gui.txt
  crawl-ref/source/rltiles/gui/backgrounds/De.png
  crawl-ref/source/startup.cc
  crawl-ref/source/tilepick-p.cc
  crawl-ref/source/tilepick.cc
Labels: enhancement

#1464 Display monster evade chance on xv
  crawl-ref/source/attack.cc
  crawl-ref/source/attack.h
  crawl-ref/source/describe.cc
  crawl-ref/source/form-data.h
  crawl-ref/source/melee-attack.cc
  crawl-ref/source/melee-attack.h
  crawl-ref/source/ranged-attack.cc
  crawl-ref/source/ranged-attack.h
Labels: help wanted, ui

#1011 Webserver: Enhance lobby_remove message
  crawl-ref/source/webserver/ws_handler.py
Labels: webtiles
