Repository crawl/crawl, pull requests merged in 2021-07, with the labels that each got.

#2001 Removed dead code ranged_attack::calc_to_hit
  crawl-ref/source/ranged-attack.cc
  crawl-ref/source/ranged-attack.h
Labels: refactor

#1965 Second Antaeus quote
  crawl-ref/source/dat/descript/quotes.txt
Labels: text

#2011 Adding new quotes to the Crawl quotes list
  crawl-ref/source/dat/descript/quotes.txt
Labels: text

#1936 Check for monsters, objects & features as soon as you move.
  crawl-ref/source/player.cc
Labels: bug, refactor

#2016 Fix some issues with "stat zero" warnings.
  crawl-ref/source/delay.cc
  crawl-ref/source/item-use.cc
  crawl-ref/source/item-use.h
Labels: bug

#2030 Some new vaults for the Hall of Blades
  crawl-ref/source/dat/des/branches/blade.des
  crawl-ref/source/dat/des/branches/elf.des
  crawl-ref/source/dat/dlua/vault.lua
Labels: vaults
