Repository crawl/crawl, pull requests merged in 2021-02, with the labels that each got.

#1718 Stop art-data.pl from rewriting files which haven't changed.
  crawl-ref/source/util/art-data.pl
Labels: build

#1732 Remove some water from mumra_spider_spiderweb
  crawl-ref/source/dat/des/branches/spider.des
Labels: vaults

#1697 New spell: Projected Weapon (L5 Translocations)
  crawl-ref/source/book-data.h
  crawl-ref/source/dat/descript/spells.txt
  crawl-ref/source/fight.cc
  crawl-ref/source/fight.h
  crawl-ref/source/melee-attack.cc
  crawl-ref/source/melee-attack.h
  crawl-ref/source/player-act.cc
  crawl-ref/source/rltiles/dc-spells.txt
  crawl-ref/source/rltiles/gui/spells/translocation/manifold_assault.png
  crawl-ref/source/spell-type.h
  crawl-ref/source/spl-cast.cc
  crawl-ref/source/spl-data.h
  crawl-ref/source/spl-transloc.cc
  crawl-ref/source/spl-transloc.h
  crawl-ref/source/spl-util.cc
Labels: gameplay

#1747 Update the des syntax doc
  crawl-ref/docs/develop/levels/syntax.txt
Labels: documentation

#1750 Tweak some Swamp witch vaults to better fit their creators' intentions
  crawl-ref/source/dat/des/branches/swamp.des
Labels: vaults

#1748 Delete some unnecessary things from travel_pathfind.
  crawl-ref/source/travel.cc
  crawl-ref/source/travel.h
Labels: refactor

#1761 Make the "1 corona" status message grammatically correct, and others.
  crawl-ref/source/mon-info-flag-name.h
  crawl-ref/source/mon-info.cc
Labels: text, ui
