Repository crawl/crawl, pull requests merged in 2021-03, with the labels that each got.

#1787 Make explore behave better with exclusions
  crawl-ref/source/travel.cc
Labels: ui

#1794 Add spell damage info to the `I!` menu and morgues
  crawl-ref/source/chardump.cc
  crawl-ref/source/spl-cast.cc
Labels: ui

#1786 Allow Chei followers to use quickblades.
  crawl-ref/source/god-item.cc
Labels: gameplay

#1809 Fix shop purchase potion/scroll stacking
  crawl-ref/source/items.cc
Labels: bug

#1808 Fix Scorpion pit Vault
  crawl-ref/source/dat/des/branches/spider.des
Labels: vaults

#1830 Enable fullscreen PWA for WebTiles on iOS
  crawl-ref/source/webserver/templates/client.html
Labels: ui

#1839 Don't nerf the warlock's mirror. Improve debugging messages & comments
  crawl-ref/source/beam.cc
Labels: documentation

#1837 Update to Blade Hands description
  crawl-ref/source/dat/descript/spells.txt
  crawl-ref/source/l-you.cc
Labels: lua, text

#1845 Supress a compiler warning on Windows
  crawl-ref/source/tilesdl.cc
Labels: build

#1857 Make acid walls "melt" icy monsters instead of burning them.
  crawl-ref/source/terrain.cc
Labels: text
