Repository crawl/crawl, pull requests merged in 2021-08, with the labels that each got.

#2041 Check for monsters, objects & features as soon as you move.
  crawl-ref/source/player.cc
  crawl-ref/source/travel.cc
Labels: refactor

#2075 Add a few more _anger_possessive_ strings
  crawl-ref/source/dat/database/rand_wpn.txt
Labels: text

#2073 Rearrange existing quotes and add new ones
  crawl-ref/source/dat/descript/quotes.txt
Labels: text, contribution

#2065 Show turn counts and real game times in lobby
  crawl-ref/source/webserver/process_handler.py
  crawl-ref/source/webserver/static/scripts/client.js
  crawl-ref/source/webserver/static/style.css
  crawl-ref/source/webserver/templates/client.html
Labels: webtiles

#2061 nicolae improves the Desolation of Salt
  crawl-ref/source/dat/des/portals/desolation.des
Labels: vaults
