Repository crawl/crawl, pull requests merged in 2021-06, with the labels that each got.

#1919 Allow zoom in via ctrl-'+'
  crawl-ref/docs/options_guide.txt
  crawl-ref/source/cmd-keys.h
Labels: ui

#1951 Fix Dj's hair on the species selection menu
  crawl-ref/source/rltiles/dc-gui.txt
Labels: bug, tiles

#1998 Add Archmagi as a randart property
  crawl-ref/source/actor.cc
  crawl-ref/source/artefact-prop-type.h
  crawl-ref/source/artefact.cc
  crawl-ref/source/describe.cc
  crawl-ref/source/output.cc
  crawl-ref/source/player-equip.cc
  crawl-ref/source/wiz-item.cc
Labels: gameplay

#2000 Corrects the description of Tin of Tremorstones
  crawl-ref/source/dat/descript/items.txt
Labels: text

#1961 Update special_room_magic_class
  crawl-ref/source/dat/des/builder/rooms.des
Labels: vaults
