Repository crawl/crawl, pull requests merged in 2021-04, with the labels that each got.

#1822 Add diablo church arrival vault
  crawl-ref/source/dat/des/arrival/large.des
Labels: vaults

#1863 Remove d:1 adder in vault
  crawl-ref/source/dat/des/variable/mini_monsters.des
Labels: vaults

#1882 Allow detransforming over water if flying
  crawl-ref/source/ability.cc
  crawl-ref/source/transform.cc
Labels: bug

#1883 Unmeld statueform merfolk boots when leaving water
  crawl-ref/source/transform.cc
Labels: bug

#1899 Very important vault.
  crawl-ref/source/dat/des/variable/mini_features.des
Labels: vaults

#1901 Create artefact_creation.md
  crawl-ref/docs/develop/artefact_creation.md
Labels: documentation
