Repository crawl/crawl, pull requests merged in 2022-01, with the labels that each got.

#2132 Use the standard names for monsters in "comes into view" messages.
  crawl-ref/source/delay.cc
  crawl-ref/source/view.cc
Labels: ui, text

#2137 Edit a vault to prevent breaking level connectivity
  crawl-ref/source/dat/des/builder/shops.des
Labels: vaults

#2309 Small tweaks to LCS tiles
  crawl-ref/source/rltiles/effect/crystal_spear0.png
  crawl-ref/source/rltiles/effect/crystal_spear1.png
  crawl-ref/source/rltiles/effect/crystal_spear2.png
  crawl-ref/source/rltiles/effect/crystal_spear3.png
  crawl-ref/source/rltiles/effect/crystal_spear4.png
  crawl-ref/source/rltiles/effect/crystal_spear5.png
  crawl-ref/source/rltiles/effect/crystal_spear6.png
  crawl-ref/source/rltiles/effect/crystal_spear7.png
Labels: tiles

#2335 Spider vaults
  crawl-ref/source/dat/des/branches/spider.des
Labels: vaults

#2054 fix: add support for Haiku
  crawl-ref/source/Makefile
  crawl-ref/source/crash.cc
  crawl-ref/source/endianness.h
  crawl-ref/source/files.cc
  crawl-ref/source/initfile.cc
Labels: build
