Repository crawl/crawl, pull requests merged in 2022-06, with the labels that each got.

#2454 New Orc ending
  crawl-ref/source/dat/des/branches/orc.des
Labels: vaults

#2546 Add several small vaults containing transporters to mini_features.des
  crawl-ref/source/dat/des/variable/mini_features.des
Labels: vaults

#2543 Update items.txt
  crawl-ref/source/dat/descript/zh/items.txt
Labels: text

#2415 Rework the static discharge formulas
  crawl-ref/source/spl-cast.cc
  crawl-ref/source/spl-damage.cc
  crawl-ref/source/spl-damage.h
  crawl-ref/source/util/monster/monster-main.cc
Labels: ui, gameplay
