Repository crawl/crawl, pull requests merged in 2023-04, with the labels that each got.

#3067 Three fixes for release CI workflows
  .github/workflows/ci.yml
  .github/workflows/deps.py
  crawl-ref/source/debian/control
  crawl-ref/source/debian/rules
Labels: bug, build

#3080 Add some new shops to shops.des
  crawl-ref/source/dat/des/builder/shops.des
Labels: vaults

#3070 Add version information for Clang
  crawl-ref/source/version.cc
Labels: build

#3001 Clear the training target before the message, rather than afterwards.
  crawl-ref/source/skills.cc
Labels: enhancement, lua
